### ISSUE TITLE
API key voor BIHZ endpoints

### ISSUE THREAD

**Issue by florisz** [florisz/BerghAdmin#65]
De 4 endpoints, misschien komen er meer, moeten een API key krijgen zodat niet iedereen maar zo naar binnen kan
Opslaan in secrets,

**Comment by mountain65** [comment]
Check op API key zit erin. Op de JBF manier. Kreeg het niet voor elkaar met echte Policies. Nu nog in de secrets zien te krijgen.

**Comment by mountain65** [comment]
Done
