### ISSUE TITLE
Password wijzigen bij eerste login met rules

### ISSUE THREAD

**Issue by florisz** [florisz/BerghAdmin#90]
rules minimale standaard iets van
>=8 characters
minimaal 1 hoofdletter
minimaal 1 cijfer
minimaal 1 leesteken

**Comment by mountain65** [comment]
Sorry, dat is echt een hele ouderwetse standaard. Gewoon een lang password van 10 of 12 tekens. Mogen ze gebruiken wat ze willen. Wat nog wel stoer zou zijn is checken bij HaveIBeenPwnd. Die hebben een lijst van veel gebruikte en veel gehackte passwords (zoals password123).

**Comment by florisz** [comment]
ja weet ik maar het moet ook niet te moeilijk voor die oude mannen zijn

**Comment by mountain65** [comment]
Gelukt. Was wel nodig om wat Scaffolding te doen van de inlog pagina en reset password pagina. En nodig om een kolom LoginCount aan de User toe te voegen. Dus ook een migration toegevoegd.

Viel nog niet mee voor een back-end-er om al die cshtml zooi aan de  praat te krijgen! ;-)
